export class MutationTypes {
  public static SET_LOADING_STATUS = 'SET_LOADING_STATUS';
  public static SET_ATHLETE_LOADING_STATUS = 'SET_ATHLETE_LOADING_STATUS';


  public static GET_ATHLETE = '[Strava-API] GET_ATHLETE';

  public static GET_ACTIVITIES = '[Strava-API] GET_ACTIVITIES';
  public static GET_ACTIVITY = '[Strava-API] GET_ACTIVITY';
  public static GET_ACTIVITY_STREAMS = '[Strava-API] GET_ACTIVITY_STREAMS';
  public static GET_ACTIVITY_ZONES = '[Strava-API] GET_ACTIVITY_ZONES';

  public static GET_ACTIVITIES_FROM_JSON = '[Local] GET_ACTIVITIES_FROM_JSON';

  public static SET_DASHBOARD_VIEWTYPE = '[Store] SET_DASHBOARD_VIEWTYPE';

  public static GET_CURRENT_PREPARATION = '[Store] GET_CURRENT_PREPARATION';

  public static SET_SELECTED_ACTIVITY = '[Store] SET_SELECTED_ACTIVITY';
  public static SET_SELECTED_RUNTYPE = '[Store] SET_SELECTED_RUNTYPE';
  public static SET_SELECTED_DISPLAYTYPE = '[Store] SET_SELECTED_DISPLAYTYPE';
  public static SET_SELECTED_CLUSTER = '[Store] SET_SELECTED_CLUSTER';
  public static SET_SHOW_EVERYTHING = '[Store] SET_SHOW_EVERYTHING';
  public static SET_FILTERBY_TYPE = '[Store] SET_FILTERBY_TYPE';
  public static SET_TIME_RANGE = '[Store] SET_TIME_RANGE';
  public static SET_DISTANCE_RANGE = '[Store] SET_DISTANCE_RANGE';


  public static REMOVE_SELECTED_TRAINING_CLUSTER = '[Store] REMOVE_SELECTED_TRAINING_CLUSTER';
  public static ADD_SELECTED_TRAINING_CLUSTER = '[Store] ADD_SELECTED_TRAINING_CLUSTER';

  public static SET_SHOWN_COMPARE_ACTIVITIES = '[Store] SET_SHOWN_COMPARE_ACTIVITIES';
  public static SET_COMPARE_TIME_RANGE = '[Store] SET_COMPARE_TIME_RANGE';
  public static TOGGLE_HISTORY_CHART_DISPLAY_MODE = '[Store] TOGGLE_HISTORY_CHART_DISPLAY_MODE';

  public static SELECT_COMPARE_WEEK = '[Store] SELECT_COMPARE_WEEK';
  public static DESELECT_COMPARE_WEEK = '[Store] DESELECT_COMPARE_WEEK';

  public static GET_RACE = '[Strava-API] GET_RACE';
}
