export class MutationTypes {
  public static INCREMENT_VALUE = 'INCREMENT_VALUE';
  public static DECREMENT_VALUE = 'DECREMENT_VALUE';
  public static RESET_VALUE = 'RESET_VALUE';

  public static GET_LIST = 'GET_LIST';

  public static GET_ACTIVITIES = '[Strava-API] GET_ACTIVITIES';
  public static GET_ACTIVITY = '[Strava-API] GET_ACTIVITY';
  public static GET_ACTIVITY_STREAMS = '[Strava-API] GET_ACTIVITY_STREAMS';

  public static SET_SELECTED_ACTIVITY = '[Store] SET_SELECTED_ACTIVITY';
  public static SET_SELECTED_ACTIVITY_FROM_LOCALSTORAGE = '[Store] SET_SELECTED_ACTIVITY_FROM_LOCALSTORAGE';
  public static SET_ACTIVITIES_FROM_LOCALSTORAGE = '[Store] SET_ACTIVITIES_FROM_LOCALSTORAGE';
}
